### ISSUE TITLE
How to install the server part into IIS?

### ISSUE THREAD

**Issue by win32nipuh** [sailro/Bdtunnel#2]
Hi Sebastien,
thank you for this great applications.

Some questions:
1. How to install bdtServer into IIS? I did not find any detail descriptions
2. What is license for bdtunnel: MIT? Do I have a permission to use part of this software and probably modify it? I'd like to embed it to my wcf service

Regards,
Oleg.

**Comment by win32nipuh** [comment]
Please close this issue. 
I have integrated bdtunnel to my WCF service which can be hosted in IIS, winservice or .NET app.
Aso, finally I have made SignalR connections can be tunneled too. 

Thank you Sebastien!

**Comment by sailro** [comment]
Sorry for my no-response. I've just relocated to the US. 
Good to ear that you were able to do something with Bdtunnel !

**Comment by win32nipuh** [comment]
Hello Sebastien,

I have integrated Bdtunnel to my WCF service, replaced loggers with log4net
because of the service uses it etc etc.
It works, thank you again.

I have one question about Bdtunnel.
It will be great if you can help me.

Now the idea is: client has a map

localhost:port1 -> remotehost1:port101
localhost:port2 -> remotehost1:port102
...

I.e. we can redirect incoming requests localhost:
port->remote_ip:remote_port

How do you think: is it possible to redirect requests via tunnel using some
rules, for example:

localhost:port1/*url1* -> remotehost1:port101
localhost:port1/*url2* -> remotehost1:port102
localhost:port1/*url3* -> remotehost1:port103

localhost:port2/*url21* -> remotehost1:port201
localhost:port2*/url31* -> remotehost1:port203

etc, i.e. using urls too.

This way we can minimize number of open ports on machine with Bdtunnel
client app what may be critical in some environments.

Thanks.

Best regards,
Oleg.




2015-12-21 17:59 GMT+01:00 Sebastien Lebreton <notifications@github.com>:
