### ISSUE TITLE
About forwarding rules

### ISSUE THREAD

**Issue by win32nipuh** [sailro/Bdtunnel#3]
Hello Sebastien,

I have integrated Bdtunnel to my WCF service, replaced loggers with log4net
because of the service uses it etc etc.
It works, thank you again.

I have one question about Bdtunnel.
It will be great if you can help me.

Now the idea is: client has a map

localhost:port1 -> remotehost1:port101
localhost:port2 -> remotehost1:port102
...

I.e. we can redirect incoming requests localhost:
port->remote_ip:remote_port

How do you think: is it possible to redirect requests via tunnel using some
rules, for example:

localhost:port1/_url1_ -> remotehost1:port101
localhost:port1/_url2_ -> remotehost1:port102
localhost:port1/_url3_ -> remotehost1:port103

localhost:port2/_url21_ -> remotehost1:port201
localhost:port2_/url31_ -> remotehost1:port203

etc, i.e. using urls too.

This way we can minimize number of open ports on machine with Bdtunnel
client app what may be critical in some environments.

Thanks.

Best regards,
Oleg.

**Comment by sailro** [comment]
The socks proxy support was added for this. Because with it you can dynamically specify ip/port.

Any chance you can use it instead of relying on static rules ?

**Comment by win32nipuh** [comment]
Ah, I see, thank you, I will try to use it.
Also, it was my next question: can I dynamically re-configure the BDTunnel client?

**Comment by sailro** [comment]
Socks proxy is on the client side. Your final application must be compatible with Socks (which is super common for ftp, www clients etc).
