### ISSUE TITLE
SignalR application<->Bdtunnel

### ISSUE THREAD

**Issue by win32nipuh** [sailro/Bdtunnel#4]
I have a Winform application working with Console hosted WCF service. They use SignalR. It works ok.
I am trying to run client via Bdtunnel to work with my WCF service.
All functionality works but SignalR does not work. 
Why it can happen? May be I can change something in Bdtunnel config?

Thank you.

**Comment by win32nipuh** [comment]
I have tested my SignalR client->BDTunnel->WCF Service and can say: Yes, it works.
Probably, sometimes need to force SingalR client to reconnect use downgrading protocol (Polling, Server Events etc). It is for Windows 7 computers.

**Comment by sailro** [comment]
Ok great!
Thanks for your investigation.
