### ISSUE TITLE
How to implement this kind of connection?

### ISSUE THREAD

**Issue by ZedZipDev** [sailro/Bdtunnel#7]
Hi Sebastien, 
I use the current implementation by this schema:
myApp->BDTClient(inititates connection to the BDTServer, forwards queries)(using forward table)->BDTServer (forwards queries)->myWCFSvc

What I'd like to do, Imagine: 
I have N machines in the Internet with myApp  and 1 VM machine in a cloud.
All clients have the settings to connect to the VM to connect to myWCFSvc.
VM has no myWCFSvc but has BDTClient installed.
It is a permanent part.
The next is a dynamic:
There are 3 machines with myWCFSvc (in 3 different offices).
I'd like to have a possibility to change the real myWCFSvc and do not touch its Firewall, do not opent additional inbound ports.
I.e. I need to initiate connection betweeen the BDTCLient and BDTServer from the BDTServer side (from office): initiate and establish bidirectional (WebSockets?) connection,  and then myClients can use this connection to work with a real myWCFSvc.
By fact end-user does not know what real myWCFSvc he uses.

Probably I even do not need the WebSockets if I have a possibility to initiate connection from the BDTServer side.

Is it possible?

**Comment by hsurana** [comment]
Hi Oleg26Dev. 
Were you able to find any solution for your scenario.  I am also looking for solution for similar case.
